name: My blog
description: A jekyll theme

# Set the following to enable these features, leave as '' to disable them
github: 'scotte/jekyll-clean'
gaaccount: ''
disqus: ''

permalink: /:year/:month/:title
paginate: 3
comments: true

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

exclude: ['README.md', 'LICENSE']
